import { useEffect, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Check, Copy, LockKeyhole, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiPut, type WhatsAppConfig } from "@/lib/api";

interface Props { config: WhatsAppConfig }
interface MetaForm { meta_app_id: string; meta_app_secret: string; meta_graph_api_url: string; meta_phone_number_id: string; meta_waba_id: string; meta_access_token: string; meta_verify_token: string }
const emptyForm = (config: WhatsAppConfig): MetaForm => ({ meta_app_id: config.meta?.meta_app_id || "", meta_app_secret: "", meta_graph_api_url: config.meta?.meta_graph_api_url || "https://graph.facebook.com/v21.0", meta_phone_number_id: config.meta?.meta_phone_number_id || "", meta_waba_id: config.meta?.meta_waba_id || "", meta_access_token: "", meta_verify_token: "" });

export default function MetaConfigForm({ config }: Props) {
  const client = useQueryClient();
  const [form, setForm] = useState<MetaForm>(() => emptyForm(config));
  const [copied, setCopied] = useState(false);
  useEffect(() => setForm(emptyForm(config)), [config.meta?.meta_app_id, config.meta?.meta_phone_number_id, config.meta?.meta_waba_id, config.meta?.meta_graph_api_url]);
  const mutation = useMutation({ mutationFn: () => apiPut<WhatsAppConfig>("/whatsapp/meta", form), onSuccess: (data) => client.setQueryData(["whatsapp-config"], data) });
  const set = (key: keyof MetaForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const copyWebhook = async () => { if (config.meta?.webhook_url) { await navigator.clipboard.writeText(config.meta.webhook_url); setCopied(true); window.setTimeout(() => setCopied(false), 1600); } };
  return <div data-testid="meta-config-form" className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]">
    <Card className="rounded-2xl border-[#E5E7E2] shadow-sm"><CardContent className="space-y-5 p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#E0F2FE] text-[#0369A1]"><LockKeyhole size={18} /></span><div><h3 className="font-heading text-xl font-bold">Meta Cloud credentials</h3><p className="mt-1 text-sm text-[#6E736D]">Save credentials per restaurant. Secret values are never returned to the browser.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>App ID</Label><Input data-testid="meta-app-id-input" value={form.meta_app_id} onChange={(event) => set("meta_app_id", event.target.value)} placeholder="1234567890" /></div><div><Label>Graph API URL</Label><Input data-testid="meta-graph-api-input" value={form.meta_graph_api_url} onChange={(event) => set("meta_graph_api_url", event.target.value)} /></div><div><Label>App Secret</Label><Input data-testid="meta-app-secret-input" type="password" value={form.meta_app_secret} onChange={(event) => set("meta_app_secret", event.target.value)} placeholder={config.meta?.meta_app_secret_masked || "Enter secret"} /><p className="mt-1 text-xs text-[#6E736D]">Leave blank to keep the saved secret</p></div><div><Label>Access Token</Label><Input data-testid="meta-access-token-input" type="password" value={form.meta_access_token} onChange={(event) => set("meta_access_token", event.target.value)} placeholder={config.meta?.meta_access_token_masked || "Enter token"} /><p className="mt-1 text-xs text-[#6E736D]">Leave blank to keep the saved token</p></div><div><Label>Phone Number ID</Label><Input data-testid="meta-phone-number-id-input" value={form.meta_phone_number_id} onChange={(event) => set("meta_phone_number_id", event.target.value)} placeholder="WhatsApp phone number ID" /></div><div><Label>WABA ID</Label><Input data-testid="meta-waba-id-input" value={form.meta_waba_id} onChange={(event) => set("meta_waba_id", event.target.value)} placeholder="WhatsApp Business Account ID" /></div><div className="sm:col-span-2"><Label>Verify Token</Label><Input data-testid="meta-verify-token-input" type="password" value={form.meta_verify_token} onChange={(event) => set("meta_verify_token", event.target.value)} placeholder={config.meta?.meta_verify_token_masked || "Webhook verification token"} /><p className="mt-1 text-xs text-[#6E736D]">Leave blank to keep the saved verify token</p></div></div><Button data-testid="save-meta-config-button" onClick={() => mutation.mutate()} disabled={mutation.isPending} className="gap-2 rounded-full bg-[#D94833] hover:bg-[#C23E2A]"><Save size={16} />{mutation.isPending ? "Saving…" : "Save Meta configuration"}</Button>{mutation.isSuccess && <p data-testid="meta-config-saved" className="text-sm font-medium text-[#2C614F]">Meta configuration saved securely.</p>}{mutation.isError && <p data-testid="meta-config-error" className="text-sm text-rose-700">Could not save Meta configuration.</p>}</CardContent></Card>
    <Card className="h-fit rounded-2xl border-[#E5E7E2] bg-[#F7FAFC] shadow-sm"><CardContent className="space-y-5 p-6"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#0369A1]">Webhook setup</p><h3 className="mt-2 font-heading text-xl font-bold">Connect this number</h3><p className="mt-2 text-sm leading-relaxed text-[#6E736D]">In Meta Developer Console, add the URL below to your WhatsApp webhook and use the same Verify Token saved here.</p></div><div><Label>Callback URL</Label><div className="mt-1 flex gap-2"><code data-testid="meta-webhook-url" className="min-w-0 flex-1 overflow-hidden rounded-lg border border-[#D7E1E8] bg-white px-3 py-2 text-xs text-[#334155]">{config.meta?.webhook_url || "Loading webhook URL…"}</code><Button data-testid="copy-meta-webhook-button" type="button" variant="outline" size="icon" onClick={() => void copyWebhook} title="Copy callback URL">{copied ? <Check size={16} /> : <Copy size={16} />}</Button></div></div><div className="space-y-2 text-sm text-[#6E736D]"><p><strong className="text-[#1A1D1A]">Subscribe fields:</strong> messages</p><p><strong className="text-[#1A1D1A]">Webhook status:</strong> {config.meta?.configured ? <span className="text-[#2C614F]">credentials saved</span> : <span>credentials required</span>}</p></div></CardContent></Card>
  </div>;
}