import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiGet, apiPut } from "@/lib/api";
interface AISettings { provider: string; model: string; personality: string; language_behavior: string; upsell_enabled: boolean; max_upsell_attempts: number; human_handoff_enabled: boolean }
export default function AISettings() { const client = useQueryClient(); const query = useQuery({ queryKey: ["ai-settings"], queryFn: () => apiGet<AISettings>("/restaurant/ai-settings") }); const [form, setForm] = useState<AISettings | null>(null); useEffect(() => { if (query.data) setForm(query.data); }, [query.data]); const mutation = useMutation({ mutationFn: () => apiPut<AISettings>("/restaurant/ai-settings", form), onSuccess: (data) => { setForm(data); client.setQueryData(["ai-settings"], data); } }); if (!form) return <p data-testid="ai-settings-loading">Loading AI settings…</p>; return <div data-testid="ai-settings-page" className="mx-auto max-w-3xl space-y-6"><div className="flex items-end justify-between"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#2C614F]"><Sparkles size={14} /> Assistant behavior</p><h1 data-testid="ai-settings-heading" className="mt-2 font-heading text-4xl font-extrabold">AI settings</h1></div><Button data-testid="save-ai-settings-button" onClick={() => mutation.mutate()} className="rounded-full bg-[#D94833] hover:bg-[#C23E2A]">Save</Button></div><Card className="rounded-2xl border-[#E5E7E2]"><CardContent className="space-y-5 p-6"><div><Label>Provider</Label><Input data-testid="ai-provider-input" value={form.provider} readOnly /></div><div><Label>Model</Label><Input data-testid="ai-model-input" value={form.model} onChange={(event) => setForm({ ...form, model: event.target.value })} /></div><div><Label>Personality</Label><Input data-testid="ai-personality-input" value={form.personality || ""} onChange={(event) => setForm({ ...form, personality: event.target.value })} /></div><div><Label>Language behavior</Label><Textarea data-testid="ai-language-input" value={form.language_behavior || ""} onChange={(event) => setForm({ ...form, language_behavior: event.target.value })} /></div><div className="grid gap-5 sm:grid-cols-2"><div><Label>Upselling enabled</Label><Input data-testid="ai-upsell-input" value={String(form.upsell_enabled)} onChange={(event) => setForm({ ...form, upsell_enabled: event.target.value === "true" })} /></div><div><Label>Max upsell attempts</Label><Input data-testid="ai-max-upsell-input" type="number" value={form.max_upsell_attempts} onChange={(event) => setForm({ ...form, max_upsell_attempts: Number(event.target.value) })} /></div></div></CardContent></Card></div>; }