import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiGet, apiPut, type Restaurant } from "@/lib/api";
export default function Settings() { const client = useQueryClient(); const query = useQuery({ queryKey: ["restaurant"], queryFn: () => apiGet<Restaurant>("/restaurant") }); const [form, setForm] = useState<Restaurant | null>(null); useEffect(() => { if (query.data) setForm(query.data); }, [query.data]); const mutation = useMutation({ mutationFn: () => apiPut<Restaurant>("/restaurant", form), onSuccess: (data) => { setForm(data); client.setQueryData(["restaurant"], data); } }); if (!form) return <p data-testid="settings-loading">Loading settings…</p>; const field = (key: keyof Restaurant, label: string) => <div><Label>{label}</Label><Input data-testid={`settings-${key}`} value={String(form[key] ?? "")} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></div>; return <div data-testid="settings-page" className="mx-auto max-w-4xl space-y-6"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#2C614F]">Workspace</p><h1 data-testid="settings-heading" className="mt-2 font-heading text-4xl font-extrabold">Restaurant settings</h1></div><Button data-testid="save-settings-button" onClick={() => mutation.mutate()} disabled={mutation.isPending} className="gap-2 rounded-full bg-[#D94833] hover:bg-[#C23E2A]"><Save size={16} /> Save</Button></div><Card className="rounded-2xl border-[#E5E7E2]"><CardContent className="grid gap-5 p-6 md:grid-cols-2">{field("name", "Restaurant name")}{field("currency", "Currency")}{field("contact_number", "Contact number")}{field("whatsapp_number", "WhatsApp number")}{field("city", "City")}{field("opening_hours", "Opening hours")}<div className="md:col-span-2">{field("address", "Address")}</div><div className="md:col-span-2"><Label>Description</Label><Textarea data-testid="settings-description" value={form.description || ""} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div><div className="md:col-span-2"><Label>AI greeting</Label><Textarea data-testid="settings-ai-greeting" value={form.ai_greeting || ""} onChange={(event) => setForm({ ...form, ai_greeting: event.target.value })} /></div></CardContent></Card></div>; }